import React from 'react'
import type { Metadata } from 'next'

import { Locale, useI18n } from '@/I18n'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const Home: React.FC = () => {
  return (
    <div>

      <main> test
      </main>
    </div>
  )
}

export default Home
